# Generated by Django 4.0.5 on 2022-08-02 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Morakhsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numorakhasi', models.IntegerField(verbose_name='شماره درخواست')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('fromdate', models.CharField(max_length=10, verbose_name='از تاریخ')),
                ('todate', models.CharField(max_length=10, verbose_name='تا تاریخ')),
                ('Comment', models.TextField(verbose_name='توضیحات ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
