# Generated by Django 4.0.5 on 2022-08-02 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Morakhsi',
            new_name='MorakhsiDetailView',
        ),
    ]
