# Generated by Django 4.0.5 on 2022-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_morakhsi_morakhsidetailview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfromation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id', models.IntegerField(verbose_name='شماره پرسنلی')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('semat', models.CharField(max_length=50, verbose_name='سمت')),
                ('start_date', models.CharField(max_length=10, verbose_name='تاریخ شروع به کار')),
                ('vaziyat', models.CharField(max_length=10, verbose_name='وضعیت تاهل')),
                ('farzand', models.ImageField(upload_to='', verbose_name='تعداد اولاد')),
            ],
        ),
    ]
