# Generated by Django 4.0.5 on 2022-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_personalinfromation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelPresenceAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('rozhafte', models.CharField(max_length=10, verbose_name='روز هفته')),
                ('personnel_id', models.IntegerField(verbose_name='کد پرسنلی')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('vaziyat', models.CharField(max_length=10, verbose_name='وضعیت')),
                ('vorod', models.DateTimeField(verbose_name='ساعت ورود')),
                ('khoroj', models.DateTimeField(verbose_name='ساعت خروج')),
                ('morakhasi_saati', models.DateTimeField(verbose_name='میزان مرخصی ساعتی')),
                ('takhir', models.DateTimeField(verbose_name=' تاخیر')),
                ('ezafe_kari', models.DateTimeField(verbose_name='اضافه کاری')),
            ],
        ),
        migrations.AlterField(
            model_name='personalinfromation',
            name='farzand',
            field=models.IntegerField(verbose_name='تعداد اولاد'),
        ),
        migrations.AlterField(
            model_name='personalinfromation',
            name='personnel_id',
            field=models.IntegerField(verbose_name='کد پرسنلی'),
        ),
    ]
