# Generated by Django 4.0.5 on 2022-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_personelpresenceabsence_vorod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='ezafe_kari',
            field=models.TimeField(verbose_name='اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='khoroj',
            field=models.TimeField(verbose_name='ساعت خروج'),
        ),
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='morakhasi_saati',
            field=models.TimeField(verbose_name='میزان مرخصی ساعتی'),
        ),
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='takhir',
            field=models.TimeField(verbose_name=' تاخیر'),
        ),
    ]
