# Generated by Django 4.0.5 on 2022-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_personelpresenceabsence_ezafe_kari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='تاریخ'),
        ),
    ]
