# Generated by Django 4.0.5 on 2022-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_personelpresenceabsence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mymembers', models.CharField(max_length=10, verbose_name='firstname')),
                ('lasname', models.CharField(max_length=10, verbose_name='namkhanevadegi')),
            ],
        ),
    ]
