# Generated by Django 4.0.5 on 2022-08-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='lasname',
            new_name='lastname',
        ),
    ]
