# Generated by Django 4.0.5 on 2022-08-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_lasname_members_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
