# Generated by Django 4.0.5 on 2022-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_members_alter_morakhsidetailview_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morakhsidetailview',
            name='numorakhasi',
        ),
        migrations.AlterField(
            model_name='morakhsidetailview',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='شماره درخواست'),
        ),
    ]
