# Generated by Django 3.1.4 on 2022-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_morakhsidetailview_numorakhasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfromation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personelpresenceabsence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
